export default [{
    id:1,
    vag:false,
    meat:'Chicken',
    price: 20.00,
    item:'Butter Chicken', 
    subtitle:'(Punjab Special)',
    description:'(Oven Cooked Chicken Cooked In Tomato Rich Gravy With Spice)',
    img:'img01.jpg',
    },
    {
    id:2,
    vag:false,
    meat:'Chicken',
    price:20.50,
    item:'Roast Pepper Chicken',
    subtitle: '(South Indian Special)',
    description:'(Chicken Cooked With Black Pepper & Curry Leaves)',
    img:'img02.jpg',
    },
    {
    id:3,
    vag:false,
    meat:'Chicken',
    price:20.00,
    item:'Nizami Handi', 
    subtitle:'(Hyderabad Special)',
    description:'(Chicken Cooked With Chef’s Special Spices)',
    img:'img03.jpg',
    },
    {
    id:4,
    vag:false,
    meat:'Chicken',
    price:20.00,
    item:'Chicken Tikka Masala', 
    subtitle:'(Lal Qila Special)',
    description:'(Oven Grilled Chicken Cooked In Tomato Rich Gravy)',
    img:'img04.jpg',
    },
    {
    id:5,
    vag:false,
    meat:'Chicken',
    price:20.50,
    item:'Bhuna Chicken', 
    subtitle:'(nz Special)',
    description:'(Chicken Roast With Hand Pounded Spices)',
    img:'img05.jpg',
    },
    {
    id:6,
    vag:false,
    meat:'Chicken',
    price:20.00,
    item:'Roasted Coconut Chicken',
    subtitle:'(Kerala Special)',
    description:'(Chicken Cooked With Roasted Coconut And Kerala Spices)',
    img:'img06.jpg', 
    },
    {
    id:7,
    vag:false,
    meat:'lamb',
    price:21.00,
    item:'Lamb Rogan Josh',
    subtitle:'(Hyderabad Special)',
    description:'(Lamb Cooked With Onion & Tomato Gravy)',
    img:'img07.jpg', 
    },
    {
    id:8,
    vag:false,
    meat:'lamb',
    price:21.00,
    item:'Lamb Kadai',
    subtitle:'(NZ Special)',
    description:'(Lamb Cooked With Fried Onion, Tomato, Capsicum In Tomato-Based Gravy)',
    img:'img08.jpg', 
    },
    {
    id:9,
    vag:false,
    meat:'lamb',
    price:25.00,
    item:'Lamb Shank',
    subtitle:'(Chefs Special)',
    description:'(Lamb Shank Cooked In Semi Gravy)',
    img:'img09.jpg',
    },
    {
    id:10,
    vag:false,
    meat:'lamb',
    price:21.50,
    item:'Lamb Bhuna Gosh',
    description:'(Lamb Roast With Hand Pounded Spices)',
    img:'img10.jpg',
    },
    {
    id:11,
    vag:true,
    meat:'vegetarian',
    price:15.50,
    item:'Dal Tadka',
    description:'(Yellow Lentils Cooked & Tempered With Garlic, Onion, Green Chilli&Tomato)',
    img:'img11.jpg',
    },
    {
    id:12,
    vag:true,
    meat:'vegetarian',
    price:16.50,
    item:'Dal Makhni',
    description:'(Mixed Boiled Lentils Tempered With Butter & Tomato Purée)',
    img:'img12.jpg',
    },
    {
    id:13,
    vag:true,
    meat:'vegetarian',
    price:19.00,
    item:'Charsi Kadai Paneer',
    description:'(Cottage Cheese Cooked With Onion, Capsicum, Fried Onion & Hand Pounded Spices)',
    img:'img13.jpg',
    },
    {
    id:14,
    vag:true,
    meat:'vegetarian',
    price:19.00,
    item:'Saag Paneer',
    description:'(Cottage Cheese Cooked With Spinach)',
    img:'img14.jpg',
    },
    {
    id:15,
    vag:true,
    meat:'vegetarian',
    price:19.00,
    item:'Angara Paneer', 
    subtitle:'(Charcoal Paneer)',
    description:'(Cottage Cheese Cooked With Charcoal Flavor)',
    img:'img15.jpg',
    },
    {
    id:16,
    vag:true,
    meat:'vegetarian',
    price:17.50,
    item:'Malai Kofta',
    description:'(Cottage Cheese Dumpling Cooked With Creamy Sauce)',
    img:'img16.jpg',
    },
    {
    id:17,
    vag:true,
    meat:'vegetarian',
    price:19.50,
    item:'Roasted Whole Cashew Masala',
    description:'(Roasted Whole Cashew Cooked With Tomato & Onion Rich Gravy)',
    img:'img17.jpg',
    },
    {
    id:18,
    vag:true,
    meat:'seafood',
    price:21.50,
    item:'Bengali Fish Masala',
    description:'(Fish Tempered With Mustard, Curry Leaves & Cooked In Onion Gravy)',
    img:'img18.jpg',
    },
    {
    id:19,
    vag:false,
    meat:'seafood',
    price:22.00,
    item:'Prawns Masala',
    description:'(Prawn Cooked With Onion, Tomato & Capsicum)',
    img:'img19.jpg',
    }
    ]
